version: "3"

dotenv: [".env"]

tasks:
  compose:
    cmds:
      - docker compose -f docker-compose.yml {{.CLI_ARGS}}

  "log_nats":
    cmds:
      - docker logs -f ${NATS_CONTAINER_NAME} --tail=10
